[package]
name = "Composia"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = "0.20.1"
winit = "0.29.15"
bytemuck = { version = "1.14", features = ["derive"] }
tokio = { version = "1.47", features = ["rt-multi-thread", "macros"] }
pollster = "0.3"
glam = { version = "0.27", features = ["bytemuck"] }
rand = { version = "0.8", features = ["small_rng"] }
